/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_nhom9;

/**
 *
 * @author Ngoc Tuan
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        radnam.setSelected(true);
        setContentPane(KhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GioiTinhbtn = new javax.swing.ButtonGroup();
        KhachHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maKHText = new javax.swing.JTextField();
        tenKHText = new javax.swing.JTextField();
        cccdText = new javax.swing.JTextField();
        soDTText = new javax.swing.JTextField();
        radnam = new javax.swing.JRadioButton();
        radnu = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KHTable = new javax.swing.JTable();
        Phong = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        AddBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));

        KhachHang.setBackground(new java.awt.Color(51, 51, 255));
        KhachHang.setMinimumSize(new java.awt.Dimension(600, 450));
        KhachHang.setPreferredSize(new java.awt.Dimension(600, 450));
        KhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Khách Hàng");
        KhachHang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 220, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(maKHText);
        jLabel2.setText("Mã KH: ");
        KhachHang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 58, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên KH:");
        KhachHang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CCCD: ");
        KhachHang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 49, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giới Tính:");
        KhachHang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Số ĐT:");
        KhachHang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 58, 30));

        maKHText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maKHText.setForeground(new java.awt.Color(255, 0, 51));
        maKHText.setPreferredSize(new java.awt.Dimension(60, 25));
        KhachHang.add(maKHText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, 30));

        tenKHText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tenKHText.setForeground(new java.awt.Color(255, 0, 51));
        tenKHText.setPreferredSize(new java.awt.Dimension(60, 25));
        KhachHang.add(tenKHText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 185, 30));

        cccdText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cccdText.setForeground(new java.awt.Color(255, 0, 51));
        cccdText.setPreferredSize(new java.awt.Dimension(60, 25));
        KhachHang.add(cccdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 223, 30));

        soDTText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soDTText.setForeground(new java.awt.Color(255, 0, 51));
        soDTText.setMinimumSize(new java.awt.Dimension(60, 25));
        KhachHang.add(soDTText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 223, 30));

        GioiTinhbtn.add(radnam);
        radnam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radnam.setForeground(new java.awt.Color(255, 255, 255));
        radnam.setText("Nam");
        KhachHang.add(radnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 192, -1, -1));

        GioiTinhbtn.add(radnu);
        radnu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radnu.setForeground(new java.awt.Color(255, 255, 255));
        radnu.setText("Nữ");
        KhachHang.add(radnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 192, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 40));
        KhachHang.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 65, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.setPreferredSize(new java.awt.Dimension(80, 40));
        KhachHang.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 137, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xóa");
        jButton3.setPreferredSize(new java.awt.Dimension(80, 40));
        KhachHang.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 208, -1, -1));

        KHTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "  Mã KH", "Tên KH", "CCCD", "Giới Tính", "Số ĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(KHTable);

        KhachHang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 610, 170));

        Phong.setBackground(new java.awt.Color(51, 51, 255));
        Phong.setMinimumSize(new java.awt.Dimension(600, 450));
        Phong.setPreferredSize(new java.awt.Dimension(600, 450));
        Phong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Loại Phòng:");
        Phong.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số Phòng:");
        Phong.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Giá Tiền:");
        Phong.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tình Trạng: ");
        Phong.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jScrollPane2.setViewportView(jTextPane1);

        Phong.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jScrollPane3.setViewportView(jTextPane2);

        Phong.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, -1));

        jScrollPane4.setViewportView(jTextPane4);

        Phong.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, -1));

        jScrollPane5.setViewportView(jTextPane5);

        Phong.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));

        AddBtn.setBackground(new java.awt.Color(51, 255, 51));
        AddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Thêm");
        AddBtn.setPreferredSize(new java.awt.Dimension(70, 25));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        Phong.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Sửa");
        jButton4.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Phong.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Xóa");
        jButton5.setPreferredSize(new java.awt.Dimension(70, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Phong.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Thoát");
        jButton6.setPreferredSize(new java.awt.Dimension(70, 25));
        Phong.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Số Phòng", "Loại Phòng", "Giá Tiền", "Tình Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable1);

        Phong.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -3, 360, 460));

        jLabel11.setBackground(new java.awt.Color(0, 255, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("THÔNG TIN PHÒNG");
        Phong.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Phong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.ButtonGroup GioiTinhbtn;
    private javax.swing.JTable KHTable;
    private javax.swing.JPanel KhachHang;
    private javax.swing.JPanel Phong;
    private javax.swing.JTextField cccdText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextField maKHText;
    private javax.swing.JRadioButton radnam;
    private javax.swing.JRadioButton radnu;
    private javax.swing.JTextField soDTText;
    private javax.swing.JTextField tenKHText;
    // End of variables declaration//GEN-END:variables
}
